on:
  push:
    branches: [ main ]
    
jobs:
  List-Branches:
    runs-on: ubuntu-latest
    name: Job para listar Branches de reposit√≥rio GitHub
    steps:
      - name: Listar Branches action step
        id: list
        uses: geovanams/list-branches-docker-action@main
        with:
          owner: 'geovanams'
          repo: 'public-repo'
